spring:
  datasource:
    url: jdbc:postgresql://dpg-cvidu515pdvs738lke3g-a.oregon-postgres.render.com:5432/portfolio_db_88um
    username: portfolio_user
    password: kVlc7c7HU7dFpk5RzGRZTQwVz8UC3P0l
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중일 경우 'update' or 'create', 운영은 'none' 추천
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true